spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
        orderService:
            maxAttempts: 5
            waitDuration: 300ms
            enable-exponential-backoff: true
            exponential-backoff-multiplier: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: true

server:
  port: 8082
